version: '3'

services:

  postgresqldb:
    image: postgres:14.3-alpine
    command: postgres -c 'max_connections=500'
    volumes:
      - $EXTERNAL_PATH/data/postgres:/var/lib/postgresql/data
    ports:
      - "8424:5432"
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - softbooks-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  nginx:
    image: abevoelker/docker-nginx-alpine-brotli
    container_name: nginx
    volumes:
      - ./data/nginx/config/nginx_brotli.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/public/angular:/var/www/angular
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/logs/nginx:/var/log/nginx
    restart: always
    networks:
      - softbooks-net
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: always
    networks:
      - softbooks-net
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    links:
      - nginx

  config:
    container_name: config
    build: ./config
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
    image: innlabkz/softbooks-config
    restart: always
    networks:
      - softbooks-net
    ports:
      - "8888:8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery:
    container_name: discovery
    build: ./discovery
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
    image: innlabkz/softbooks-discovery
    restart: always
    networks:
      - softbooks-net
    depends_on:
      - config
    links:
      - config
    ports:
      - "8761:8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    container_name: gateway
    build: ./gateway
    image: innlabkz/softbooks-gateway
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - CORS_URL=$CORS_URL
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - config
    networks:
      - softbooks-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  file-service:
    image: innlabkz/softbooks-file-service:latest
    volumes:
      - $EXTERNAL_PATH/files:$FILE_PATH
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - FILE_SERVICE_PASSWORD=$FILE_SERVICE_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_SERVER=$POSTGRES_SERVER
      - FILE_PATH=$FILE_PATH
    networks:
      - softbooks-net
    restart: always
    depends_on:
      - config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    image: innlabkz/softbooks-auth-service:latest
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - USER_SERVICE_PASSWORD=$USER_SERVICE_PASSWORD
      - FILE_SERVICE_PASSWORD=$FILE_SERVICE_PASSWORD
      - CAR_SERVICE_PASSWORD=$CAR_SERVICE_PASSWORD
      - MAIL_SERVICE_PASSWORD=$MAIL_SERVICE_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_SERVER=$POSTGRES_SERVER
    networks:
      - softbooks-net
    restart: always
    depends_on:
      - config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  user-service:
    image: innlabkz/softbooks-user-service:latest
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - USER_SERVICE_PASSWORD=$USER_SERVICE_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_SERVER=$POSTGRES_SERVER
      - FILE_PATH=$FILE_PATH
    networks:
      - softbooks-net
    restart: always
    depends_on:
      - config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  car-service:
    image: innlabkz/softbooks-car-service:latest
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - CAR_SERVICE_PASSWORD=$CAR_SERVICE_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_SERVER=$POSTGRES_SERVER
    networks:
      - softbooks-net
    restart: always
    depends_on:
      - config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  mail-service:
    image: innlabkz/mugalim-mail-service:latest
    environment:
      - CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
      - MAIL_SERVICE_PASSWORD=$MAIL_SERVICE_PASSWORD
    networks:
      - softbooks-net
    restart: always
    depends_on:
      - config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

networks:
  softbooks-net:
