spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
  profiles:
    active: git
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888