spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/projetto
    username: postgres
    password:

    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      location: /Users/yerasyl/Desktop/easywash-file

sketchfab:
  token: 95b2ac087c20456e96f01432d30af82b

server:
  servlet:
    context-path: /file
  port: 6070

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: file-service
      client-secret: ${FILE_SERVICE_PASSWORD}
      access-token-uri: http://localhost:5001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
