name: Build and Push Docker Image

on:
  push:
    branches:
      - production

jobs:
  user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get changed files in the user-service
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: ./user-service/**

      - name: Set up Java
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./user-service
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Login to Docker Hub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: innlabkz/projetto-user-service:latest

#  book-service:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 3
#
#      - name: Get changed files in the book-service
#        id: changed-files-specific
#        uses: tj-actions/changed-files@v35
#        with:
#          files: ./book-service/**
#
#      - name: Set up Java
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Build with Maven
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        working-directory: ./book-service
#        run: mvn clean package -X -Dmaven.test.skip=true
#
#      - name: Login to Docker Hub
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        uses: docker/build-push-action@v4
#        with:
#          context: ./book-service
#          push: true
#          tags: innlabkz/projetto-book-service:latest

  car-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Get changed files in the car-service
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: ./car-service/**

      - name: Set up Java
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./car-service
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Login to Docker Hub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./car-service
          push: true
          tags: innlabkz/projetto-car-service:latest

  file-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Get changed files in the file-service
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: ./file-service/**

      - name: Set up Java
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./file-service
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Login to Docker Hub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./file-service
          push: true
          tags: innlabkz/projetto-file-service:latest

  auth-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Get changed files in the auth-service
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: ./auth-service/**

      - name: Set up Java
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./auth-service
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Login to Docker Hub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: innlabkz/projetto-auth-service:latest

  mail-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Get changed files in the auth-service
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: ./mail-service/**

      - name: Set up Java
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./mail-service
        run: mvn clean package -X -Dmaven.test.skip=true

      - name: Login to Docker Hub
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./mail-service
          push: true
          tags: innlabkz/projetto-mail-service:latest
